### ISSUE TITLE
.ipynbファイルの方を何点修正したい！

### ISSUE THREAD

**Issue by LiZijing0929** [naokigarashi/Twitter_API_Academic#2]
ISSUESを使ってみたいので、ipynbファイルを対象にしたいと思います

- エラーが出た時に、収集できた分をまずCSVファイルに保存できるように
- 出力する前にJPT時間に変換
- 書き換え防止のため違うファイル名を作る
- Rate Limitを超えた場合、再リクエストまでの時間を問い合わせできるように

#3

**Comment by LiZijing0929** [comment]
@naokigarashi メンバーに入れてくれるとありがたいです！（PUSHする前に気づいた笑

**Comment by naokigarashi** [comment]
パスワードミスって、アクセスできなくなっちゃたので少々お待ちください笑笑

**Comment by LiZijing0929** [comment]
> パスワードミスって、アクセスできなくなっちゃたので少々お待ちください笑笑

メールきました！ありがとうございます！！
