### ISSUE TITLE
格納されたcsvファイルについて

### ISSUE THREAD

**Issue by naokigarashi** [naokigarashi/Twitter_API_Academic#5]
![image](https://user-images.githubusercontent.com/80380818/115178904-2c036980-a10d-11eb-8ce3-799f05ada89c.png)

csvファイルについて、
・"text"列が2つ。1つは事前に消しておきたい。
・時刻は古い順に並べたい。

**Comment by LiZijing0929** [comment]
確かにテキスト列が二つある点は気になりますね！

> ・"text"列が2つ。1つは事前に消しておきたい。

について、浅野さんのコードを参照しようとしたら、
```
        getter = TweetsGetter.bySearch(keyword)

        list_text = []
        list_id = []
        list_user_screenname = []
        list_created_at = []
        list_coordinates = []

        for tweet in getter.collect(total = 1000000):
            list_text.append(tweet['text'])
            list_id.append(tweet['id'])
            list_user_screenname.append(tweet['user']['screen_name'])
            list_created_at.append(tweet['created_at'])
            list_coordinates.append(tweet['coordinates'])
```

のように、先にlistに格納してからDataFrameにappendする方法を使ったことを気付きました。
こうすれば
> ・"text"列が2つ。1つは事前に消しておきたい。

解決できるかもしれませんね。

**Comment by naokigarashi** [comment]
すごいです！ありがとうございます。
すみません最近手伝っていなくて笑
